<a href="https://colab.research.google.com/github/Noran69/Exercises-Assignments/blob/main/Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
# Load a dataset (e.g., Titanic, Iris, or any dataset of your choice) into a Pandas DataFrame.
df = pd.read_csv("/content/sample_data/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
#Display the first 5 rows and the last 5 rows of the dataset.
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
# Check the dimensions of the dataset (number of rows and columns).
df.shape

(891, 12)

In [6]:
# Display the column names and data types of each column.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
# Check for missing values in the dataset.
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
#Handle missing values by either filling them with a suitable value (e.g., mean, median, or mode) or dropping rows/columns with missing values.
df = df.fillna(0)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [9]:
#Remove duplicate rows from the dataset.
df = df.drop_duplicates()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

In [10]:
# Convert columns to appropriate data types (e.g., convert strings to datetime or categorical variables).
df['Age'] = df['Age'].replace('zero', 0).astype(int)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,0,Q

In [11]:
# Rename columns to make them more descriptive.
df = df.rename(columns={'Pclass': 'Passenger Class'})
df

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,0,Q

In [12]:
# Drop unnecessary columns from the dataset.
df = df.drop(['Ticket'], axis=1)
df

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,7.7500,0,Q

In [13]:
#Create a new column based on existing columns (e.g., calculate a derived metric).
df['Fare_Per_Person'] = df['Fare'] / df['Passenger Class']
df

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Fare_Per_Person
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,7.2500,0,S,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,71.2833,C85,C,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,7.9250,0,S,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,53.1000,C123,S,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,8.0500,0,S,2.683333
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,13.0000,0,S,6.500000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,30.0000,B42,S,30.000000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,23.4500,0,S,7.816667
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,30.0000,C148,C,30.000000
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,7.7500,0,Q,2.583333

In [14]:
#Filter rows based on a condition (e.g., select rows where a column value is greater than a threshold).
df[df['Age'] > 18]

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Fare_Per_Person
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,7.2500,0,S,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,71.2833,C85,C,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,7.9250,0,S,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,53.1000,C123,S,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,8.0500,0,S,2.683333
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39,0,5,29.1250,0,Q,9.708333
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,13.0000,0,S,6.500000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,30.0000,B42,S,30.000000
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,30.0000,C148,C,30.000000
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,7.7500,0,Q,2.583333

In [15]:
# Sort the dataset by one or more columns.
df.sort_values(by='Age')

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Fare_Per_Person
667,668,0,3,"Rommetvedt, Mr. Knud Paust",male,0,0,0,7.7750,0,S,2.591667
128,129,1,3,"Peter, Miss. Anna",female,0,1,1,22.3583,F E69,C,7.452767
533,534,1,3,"Peter, Mrs. Catherine (Catherine Rizk)",female,0,0,2,22.3583,0,C,7.452767
284,285,0,1,"Smith, Mr. Richard William",male,0,0,0,26.0000,A19,S,26.000000
538,539,0,3,"Risien, Mr. Samuel Beard",male,0,0,0,14.5000,0,S,4.833333
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,0,3,"Connors, Mr. Patrick",male,70,0,0,7.7500,0,Q,2.583333
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71,0,0,49.5042,0,C,49.504200
96,97,0,1,"Goldschmidt, Mr. George B",male,71,0,0,34.6542,A5,C,34.654200
851,852,0,3,"Svensson, Mr. Johan",male,74,0,0,7.7750,0,S,2.591667
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80,0,0,30.0000,A23,S,30.000000

In [16]:
# Group the dataset by a categorical column and calculate summary statistics (e.g., mean, median, count) for each group.
df.groupby('Sex')['Age'].mean()

Sex
female    23.194268
male      24.103986
Name: Age, dtype: float64

In [17]:
# Use the apply() function to apply a custom function to a column.
df['Fare'] = df['Fare'].apply(lambda x: x * 2)
df

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Fare_Per_Person
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,14.5000,0,S,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,142.5666,C85,C,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,15.8500,0,S,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,106.2000,C123,S,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,16.1000,0,S,2.683333
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,26.0000,0,S,6.500000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,60.0000,B42,S,30.000000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,46.9000,0,S,7.816667
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,60.0000,C148,C,30.000000
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,15.5000,0,Q,2.583333

## **Section 4: Data Aggregation**
In this section, you will aggregate and summarize the dataset.

### **Tasks:**
1. Calculate the mean, median, and standard deviation for numerical columns.
2. Use the `groupby()` function to group the dataset by a categorical column and calculate the sum and mean for numerical columns.
3. Create a pivot table to summarize the dataset.
4. Use the `crosstab()` function to create a cross-tabulation of two categorical columns.
5. Calculate the correlation matrix for numerical columns.

---

In [19]:
# Calculate the mean, median, and standard deviation for numerical columns.
df.describe()

,PassengerId,Survived,Passenger Class,Age,SibSp,Parch,Fare,Fare_Per_Person
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,23.783389,0.523008,0.381594,64.408416,25.046650
std,257.353842,0.486592,0.836071,17.597344,1.102743,0.806057,99.386857,51.245594
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,6.000000,0.000000,0.000000,15.820800,2.641667
50%,446.000000,0.000000,3.000000,24.000000,0.000000,0.000000,28.908400,6.325000
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,62.000000,23.183333
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,1024.658400,512.329200

In [21]:

df.groupby('Sex').mean(numeric_only=True)

,PassengerId,Survived,Passenger Class,Age,SibSp,Parch,Fare,Fare_Per_Person
Sex,,,,,,,,
female,431.028662,0.742038,2.159236,23.194268,0.694268,0.649682,88.959636,36.892970
male,454.147314,0.188908,2.389948,24.103986,0.429809,0.235702,51.047787,18.599952

In [22]:
# Create a pivot table to summarize the dataset.
df.pivot_table(index='Sex', values='Age', aggfunc=['mean', 'median'])

             mean median
              Age    Age
Sex
female  23.194268   24.0
male    24.103986   25.0

In [23]:
# Use the crosstab() function to create a cross-tabulation of two categorical columns.
pd.crosstab(df['Sex'], df['Survived'])

Survived    0    1
Sex
female     81  233
male      468  109

In [25]:
# Calculate the correlation matrix for numerical columns.
numerical_df = df.select_dtypes(include=['number'])
correlation_matrix = numerical_df.corr()
correlation_matrix

,PassengerId,Survived,Passenger Class,Age,SibSp,Parch,Fare,Fare_Per_Person
PassengerId,1.000000,-0.005007,-0.035144,0.038220,-0.057527,-0.001652,0.012658,0.014156
Survived,-0.005007,1.000000,-0.338481,0.010508,-0.035322,0.081629,0.257307,0.267627
Passenger Class,-0.035144,-0.338481,1.000000,-0.361566,0.083081,0.018443,-0.549500,-0.598631
Age,0.038220,0.010508,-0.361566,1.000000,-0.184593,-0.049061,0.135663,0.166958
SibSp,-0.057527,-0.035322,0.083081,-0.184593,1.000000,0.414838,0.159651,0.062602
Parch,-0.001652,0.081629,0.018443,-0.049061,0.414838,1.000000,0.216225,0.145265
Fare,0.012658,0.257307,-0.549500,0.135663,0.159651,0.216225,1.000000,0.988725
Fare_Per_Person,0.014156,0.267627,-0.598631,0.166958,0.062602,0.145265,0.988725,1.000000


## **Section 5: Data Visualization**
In this section, you will create visualizations to explore and present the dataset.

### **Tasks:**
1. Create a histogram for a numerical column.
2. Create a bar plot to visualize the distribution of a categorical column.
3. Create a scatter plot to explore the relationship between two numerical columns.
4. Create a box plot to visualize the distribution of a numerical column across different categories.
5. Create a heatmap to visualize the correlation matrix.

---

## **Section 6: Real-World Application**
In this section, you will apply Pandas to solve a real-world problem.

### **Tasks:**
1. Load a real-world dataset (e.g., sales data, customer data, or any dataset of your choice).
2. Perform exploratory data analysis (EDA) by calculating summary statistics and creating visualizations.
3. Clean and preprocess the dataset (handle missing values, remove duplicates, etc.).
4. Answer specific business questions using the dataset (e.g., "What is the total revenue by region?" or "Which product category has the highest sales?").
5. Write a brief report summarizing your findings.

---